### ISSUE TITLE
Incorrect module name in qrcode.app: reedsolomon

### ISSUE THREAD

**Issue by michaeljforster** [komone/qrcode#3]
Problem: Adding current commit to rebar.config and doing rebar compile gives:
    ...
    ERROR: One or more modules listed in qrcode.app are not present in ebin/*.beam:
	* reedsolomon

Solution: Changed "reedsolomon" to "qrcode_reedsolomon" in modules entry of ebin/qrcode.app.

**Comment by komone** [comment]
Fixed to please rebar
