### ISSUE TITLE
exception qrcode:encode no function clause matching qrcode_matrix:encode_bits0

### ISSUE THREAD

**Issue by yandrey** [komone/qrcode#6]
Some binary strings generate exception of qrcode:encode in qrcode_matrix:encode_bits0 

``` erlang
exception error: no function clause matching 
                    qrcode_matrix:encode_bits0([d,d,1,0,0,0,0,1,1,1,1,0,1,0,0,
                                                1,0,1,0,0,0,0,0,0,1,0,1,0|...],
                                               <<0,0,0,0,0,0,0,0,0,0,0,0,0,0,
                                                 0,0,0,0,0,0,0,254,76,29,191,
                                                 128,65,...>>) 
```

first parameter is [d,d,1,1,0,1,1,0,0,0,0,1,0,1,1,0,1,0,0,0,1,1,1,0,0,1,0,1,1,1,1,1,1]
and H = d is not integer, it doesn't match neither `encode_bits0([H|T], Acc) when is_integer(H)` nor `encode_bits0([], Acc)`

**Comment by komone** [comment]
This looks like the earlier data embedding didn't fully complete. Do you have an example input that causes this failure?

**Comment by komone** [comment]
See Issue #8
